### ISSUE TITLE
Error after version 1.2.6 with nested properties 

### ISSUE THREAD

**Issue by liacolo** [tghamm/dynamic-linq-query-builder#100]
Hi, I Found that after version 1.2.6 filters by nested fields like "Person.Name" stopped working.  

I was debugging and I find that the error is in line 128 of QueryBuilder.cs, Query in filteredResults throws the next error 

https://github.com/tghamm/dynamic-linq-query-builder/blob/d177fff0632dd754eeb83f5d2ef55c7cc4e5d926/Castle.DynamicLinqQueryBuilder/QueryBuilder.cs#L128

'((Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<Entity>)filteredResults).DebugView.Query' threw an exception of type 'System.InvalidOperationException'

I guess the error is caused by including (Not((item.Account == null)) AndAlso in expression

**Comment by tghamm** [comment]
Hi @liacolo here's a unit test that uses EF Core and uses nested filtering and passes.  Can you provide some additional information about what you're seeing?

https://github.com/tghamm/dynamic-linq-query-builder/blob/094d60563384221aea66cc635a4db6736a3d31b5/Castle.DynamicLinqQueryBuilder.Tests/ORM/ORMTests.cs#L127-L153

**Comment by tghamm** [comment]
Hi @liacolo this may be an issue with the way you've written the query.  EF Core doesn't eager load, and you're transforming the result with a `Select` to a DTO before you filter.  For this to work correctly, I'd expect you'd either need to `Include`, or use `BuildQuery` directly on the EF graph before you `Select` it out to a DTO, though even then I suspect you'd need to `Include` because of the depth.  Are you saying that this is a new behavior though in 1.2.6/1.2.7?

**Comment by liacolo** [comment]
Hi, thanks for your response. 

I'm transforming with `Select` before calling `BiuldQuery` because I need to be able to filter by some calculated fields. This used to work fine before version 1.2.6. After updating to 1.2.6+ the same query started to fail.

In the next example we want to filter by Person.Id and/or CreditCardExpirationDate :


```
context.MyObject.select(s => new myObjectDto {
Id = s.Id, 
Person = new PersonDto
  { 
  Description = s.Person.Description, 
  Id = s.Person.Id, 
  CreditCardExpirationDate = s.PaymentMethod != null && (s.PaymentMethod is CreditCard) ? ((CreditCard)s.PaymentMethod).ExpirationDate : System.DateTime.UtcNow 
  }
} )
```

**Comment by tghamm** [comment]
@liacolo thanks for the detailed example.  Can you tell me what version of EF Core/.Net/SQL you're using?  I'll likely just revert the change made in 1.2.6 that caused this, but I'd like to be able to reproduce it locally first just so I know that I've gotten it worked out for sure.  Thanks!

**Comment by liacolo** [comment]
We are using EF core/EntityFrameworkCore.SqlServer 6.0.4 and .NET 6.0.

Let me know if you can reproduce it. Thanks

**Comment by tghamm** [comment]
@liacolo this should be addressed now in the latest release.  Check out the release notes if you need to query for null checks in CLR objects, which is what was introduced in 1.2.6.  In any case, 1.2.8 should return the 1.2.5 behavior you had, along with the CultureInfo benefits you got in 1.2.7.  Let me know if you run into any issues.  Thanks for your help.

**Comment by liacolo** [comment]
Ok I'm already applying the new version for testing. Thank you very much again for helping us.

**Comment by liacolo** [comment]
Hello, I tested the new version but the error persists when filtering by a collection of values, for instance, with the in operator and a collection of strings as value. I was debugging the code and found that in `BuildNestedExpression` `AndAlso` is still being added in this case.

https://github.com/tghamm/dynamic-linq-query-builder/blob/8187d4f3c35a8f8f4ee7178365d1ab8fac116e1e/Castle.DynamicLinqQueryBuilder/QueryBuilder.cs#L303

**Comment by tghamm** [comment]
Gotcha, it looks like another case of attempting to do the same thing.  This should be a fairly straight forward fix, but if possible, can you lay out a test case for me?  I'm having trouble getting a reproduction case, despite it being pretty obvious which change is responsible for the regression. Thanks!

**Comment by tghamm** [comment]
Also, some of these EF specific cases don't pop up in unit tests and sneak through, apologies for the inconvenience.

**Comment by liacolo** [comment]
I Think you can use the same store and products case. Searching one store by product Name in it.

```
 var storeFilter = new QueryBuilderFilterRule
            {
                Condition = "and",
                Rules = new List<QueryBuilderFilterRule>
                {
                    new QueryBuilderFilterRule
                    {
                        Condition = "and",
                        Field = "Products.ProductName",
                        Id = "Products.ProductName",
                        Input = "NA",
                        Operator = "in",
                        Type = "string",
                        Value = new[] { "Car Tire" }
                    }
                }
            };
```

**Comment by tghamm** [comment]
@liacolo ok, was able to reproduce.  Are you in a position to test off of the master branch directly?  I can either wait for you to test to confirm we're good, or issue a new release, but this pretty much optionalizes all changes between 1.2.5 and now except the CultureInfo changes.  I just pushed code that should fix it, let me know your preference re: testing.  Thanks!

**Comment by liacolo** [comment]
I tested with the master branch and it seems to be working fine. Thanks!

**Comment by tghamm** [comment]
Great, I'll put out a release tonight or tomorrow morning, appreciate your assistance working through it.

**Comment by tghamm** [comment]
New release issued, thanks again, feel free to raise another issue if you find anything else!
